name: 🐞 Bug
description: File a bug/issue
title: '[BUG] <title>'
labels: [bug, NEW]
body:
    - type: checkboxes
      attributes:
          label: Is there an existing issue for this?
          description: Please [search here](https://github.com/Accenture/sfmc-devtools/issues) to see if an issue already exists for your problem.
          options:
              - label: I have searched the existing issues
                required: true
    - type: textarea
      attributes:
          label: Current Behavior
          description: A clear & concise description of what you're experiencing.
      validations:
          required: false
    - type: textarea
      attributes:
          label: Expected Behavior
          description: A clear & concise description of what you expected to happen.
      validations:
          required: false
    - type: textarea
      attributes:
          label: Steps To Reproduce
          description: Steps to reproduce the behavior.
          value: |
              1. Go to '...'
              2. Click on '....'
              3. Run '...'
              4. See error...
      validations:
          required: false
    - type: dropdown
      id: version
      attributes:
          label: Version
          description: What version of our software are you running? (mcdev --version)
          options:
              - 4.1.4
              - 4.1.3
              - 4.1.2
              - 4.1.1
              - 4.1.0
              - 4.0.2
              - 4.0.1
              - 4.0.0
              - 3.1.3
              - 3.1.2
              - 3.1.1
              - 3.1.0
              - 3.0.3
              - 3.0.2
              - 3.0.1
              - develop-branch
      validations:
          required: true
    - type: textarea
      attributes:
          label: Environment
          description: |
              examples:
                - **Operating system (Windows/Mac/Linux/...)**: Windows 10
                - **Node (node --version)**: 13.14.0
                - **npm (npm --version)**: 7.6.3
          value: |
              - OS:
              - Node:
              - npm:
      validations:
          required: false
    - type: checkboxes
      attributes:
          label: Participation
          options:
              - label: I am willing to submit a pull request for this issue.
                required: false
    - type: textarea
      attributes:
          label: Additional comments
          description: Is there anything else that's important for the team to know?
