#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# ### git commit message template ###
git config commit.template .git/templatemessage
TICKETID=`git rev-parse --abbrev-ref HEAD | LC_ALL=en_US.utf8 grep -oP '((feature|bug|bugfix|fix|hotfix|task|chore)\/)\K\d{1,7}'`
echo "[POST_CHECKOUT] Setting template commit to $TICKETID"
echo "#$TICKETID: " > ".git/templatemessage"

echo "[POST-CHECKOUT-#1]"
echo $1
echo "[POST-CHECKOUT-#2]"
echo $2
echo "[POST-CHECKOUT-#3]"
echo $3

# ### run npm install ###
IFS=$'\n'
# extract all paths to package-lock.json files 
# $1 is the new HEAD pointer
# $2 is the previous HEAD pointer
echo "[POST-CHECKOUT-#4]"
echo "git diff --name-only $1 $2 | grep -E '(^package-lock\.json)'"
echo "[POST-CHECKOUT-5]"

PACKAGES=`git diff --name-only $1 $2 | grep -E '(^package-lock\.json)'`
echo "[POST-CHECKOUT-6]"

if [[ ${PACKAGES[@]} ]]; then
  for package in $PACKAGES; do
    echo "[POST-CHECKOUT]"
    echo "📦 $package was changed. Running npm install to update your dependencies..."
    npm install
  done
else
  echo "📦 All packages up-to-date. No need to run npm install."
fi