#!/bin/sh
# ### run npm install ###
. "$(dirname "$0")/_/husky.sh"

echo "[POST-MERGE-#1]"
echo $1
echo "[POST-MERGE-#2]"
echo $2
echo "[POST-MERGE-#3]"
echo $3

IFS=$'\n'
# extract all paths to package-lock.json files 
PACKAGES=`git diff --name-only HEAD^1 HEAD | grep -E '(^package-lock\.json)'`
echo "[POST-MERGE-4]"

if [[ ${PACKAGES[@]} ]]; then
  for package in $PACKAGES; do
    echo "[POST-MERGE]"
    echo "📦 $package was changed. Running npm install to update your dependencies..."
    npm install
  done
else
  echo "📦 All packages up-to-date. No need to run npm install."
fi